import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import "react-quill/dist/quill.snow.css";
import styled from "styled-components";
import { useState, useMemo } from "react";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const ReactQuill = dynamic(() => import("react-quill"), { ssr: false });
  const modules = {
    toolbar: [
      [{ header: [1, 2, false] }],
      ["bold", "italic", "underline", "strike", "blockquote"],
      [{ list: "ordered" }, { list: "bullet" }],
      ["link", "image"],
    ],
  };

  const formats = [
    "header",
    "bold",
    "italic",
    "underline",
    "strike",
    "blockquote",
    "list",
    "bullet",
    "indent",
    "link",
    "image",
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <Container>
          <TitleHeader>This is the title</TitleHeader>

          <RichTextEditorToolBar></RichTextEditorToolBar>
          <ReactQuill theme="snow" formats={formats} modules={modules}>
            <div className="my-editing-area" style={{ border: "none" }}>
              lmo
            </div>
          </ReactQuill>
        </Container>
      </Wrapper>
    </>
  );
}

const RichTextEditorToolBar = styled.div`
  width: 464px;
  height: 40px;
  /* UI Properties */
  background: var(---ffffff) 0% 0% no-repeat padding-box;
  background: #ffffff 0% 0% no-repeat padding-box;
  border: 1px solid #e7f1e9;
  border-radius: 5px;
  opacity: 1;
`;

// const WidgetContainer = styled.div`
//   width: 32px;
//   height: 32px;
//   background: #e7f1e9 0% 0% no-repeat padding-box;
//   border-radius: 16px;
//   opacity: 1;
//   display: flex;
//   justify-content: center;
//   align-items: center;
// `;

const TitleHeader = styled.h1`
  font: var(--unnamed-font-style-normal) normal var(--unnamed-font-weight-bold)
    24px/36px var(--unnamed-font-family-open-sans);
  letter-spacing: var(--unnamed-character-spacing-0);
  color: var(--unnamed-color-343e37);
  text-align: left;
  font: normal normal bold 24px/36px Open Sans;
  letter-spacing: 0px;
  color: #343e37;
  opacity: 1;
`;

const Container = styled.div`
  width: 662px;
  height: 813px;
  background: #fafafa 0% 0% no-repeat padding-box;
  border: 1px solid #e7f1e9;
  border-radius: 4px;
  opacity: 1;
  padding: 16px;
`;
const Wrapper = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
`;
